FROM python:3.12-slim
WORKDIR /app

COPY pyproject.toml .
COPY src/ src/
COPY pipelines/ pipelines/

RUN pip install --no-cache-dir -e ".[pipeline]"

ENV RUNNING_IN_CONTAINER=true

ENTRYPOINT ["python"]
